spring:
  datasource:
    url: ${db_url_test}
    username: ${db_username_test}
    password: ${db_password_test}
    hikari:
      minimum-idle: 0
      maximum-pool-size: 5
      idle-timeout: 30000
      max-lifetime: 60000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 445785093291-qpem07lfk7p4kcispbt3758c3f1ero0i.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo



gemini:
  api:
    url: ${gemini_url}
    key: ${gemini_key}


jwt:
  key: "mYiADZOy9Hq5pTfomhj9hPUJLGAN/ZB6AZ4yoHfCtN0f8DaNQr6+4qeaJ9YfMK4ZbX85J3ao6TotW+jrLKLGeafpaYYLn2mmrYOB/1mJzhQYEaf883PtWAIwnTwHpPuEsJAhyHwEtlTvy++pZA+0bns66RUDBk80bJUA4JhJUI8="
logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE
